insert into public.templates (name, description, category, content_json, is_system_template)
values
  ('Lecture Note', 'Structured class or course note.', 'study', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Topic"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Key Concepts"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph"}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Summary"}]}]}', true),
  ('Programming Study Note', 'Concept, syntax, examples, and practice.', 'programming', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Topic"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Concept"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Example"}]},{"type":"codeBlock","attrs":{"language":"typescript","detectedType":"code","showLineNumbers":true,"wordWrap":false,"source":"manual","confidence":1},"content":[{"type":"text","text":"// Add example here"}]}]}', true),
  ('Cybersecurity Lab Note', 'Lab objective, steps, findings, and mitigation.', 'cybersecurity', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Lab Title"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Objective"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Steps"}]},{"type":"codeBlock","attrs":{"language":"bash","detectedType":"terminal","showLineNumbers":true,"wordWrap":true,"source":"manual","confidence":1},"content":[{"type":"text","text":"# Add commands here"}]}]}', true),
  ('CTF Write-up', 'Challenge notes from recon to lessons learned.', 'cybersecurity', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Challenge Name"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Recon"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Exploitation Steps"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Lessons Learned"}]}]}', true),
  ('Bug/Error Fix Note', 'Capture context, error, root cause, and fix.', 'debugging', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Error Title"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Error Message"}]},{"type":"codeBlock","attrs":{"language":"plaintext","detectedType":"plain_text","showLineNumbers":true,"wordWrap":true,"source":"manual","confidence":1}},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Fix"}]}]}', true),
  ('SQL Learning Note', 'SQL concept, query pattern, example data, and practice.', 'database', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"SQL Topic"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Query Pattern"}]},{"type":"codeBlock","attrs":{"language":"sql","detectedType":"sql","showLineNumbers":true,"wordWrap":false,"source":"manual","confidence":1},"content":[{"type":"text","text":"SELECT * FROM table_name;"}]}]}', true),
  ('Project Documentation', 'Overview, setup, architecture, features, and security notes.', 'documentation', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Project Name"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Overview"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Setup"}]},{"type":"codeBlock","attrs":{"language":"bash","detectedType":"terminal","showLineNumbers":true,"wordWrap":true,"source":"manual","confidence":1},"content":[{"type":"text","text":"npm install\nnpm run dev"}]}]}', true),
  ('Command Cheat Sheet', 'Reusable command categories, descriptions, and examples.', 'commands', '{"type":"doc","schemaVersion":1,"content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Command Cheat Sheet"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Category"}]},{"type":"codeBlock","attrs":{"language":"bash","detectedType":"terminal","showLineNumbers":true,"wordWrap":true,"source":"manual","confidence":1},"content":[{"type":"text","text":"git status"}]}]}', true);
